tracktask/tasks/forms.py
"""
Title:      forms.py
Desc:       holds all task form methods
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class TaskForm(FlaskForm):
    task_name = StringField('Task Name',
                            validators=[DataRequired()], )
    text = TextAreaField('Description',
                         validators=[DataRequired()], )
    submit = SubmitField('Submit Task')

tracktask/main/routes.py
"""
Title:      routes.py
Desc:       contains route functions for running base application methods
"""
from flask import render_template, request, Blueprint

from tracktask.models import Task

main = Blueprint('main', __name__)


# - - - - - - - - - - - - - - Main Methods - - - - - - - - - - - - - - #

@main.route("/", methods=['GET', 'POST', 'PUT'])
@main.route("/index", methods=['GET', 'POST', 'PUT'])
def index():
    """Index/Home page"""
    page = request.args.get('page', 1, type=int, )
    tasks = Task.query \
        .order_by(Task.date_posted.desc()) \
        .paginate(page=page,
                  per_page=4)  # limits number of items per page
    return render_template('index.jinja2', tasks=tasks)


@main.route("/about", methods=['GET'])
def about():
    """About page"""
    return render_template('about.jinja2', title='About')

tracktask/tasks/routes.py
"""
Title:      routes.py
Desc:       contains route functions that pertain to the tasks model
"""
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from tracktask import db
from tracktask.models import Task
from tracktask.tasks.forms import TaskForm

tasks = Blueprint('tasks', __name__)


# - - - - - - - - - - - - - - Task Methods - - - - - - - - - - - - - - #


@tasks.route("/task/<int:task_id>")
def task(task_id):
    queried_task = Task.query.get_or_404(task_id)
    return render_template('task.jinja2',
                           task_name=queried_task.task_name,
                           task=queried_task, )


@tasks.route("/task/<int:task_id>/update", methods=['GET', 'POST'])
@login_required
def update_task(task_id):
    queried_task = Task.query.get_or_404(task_id)

    # verify that the user requesting to update is the original author
    if queried_task.author != current_user:
        abort(403)
    form = TaskForm()

    if form.validate_on_submit():
        queried_task.task_name = form.task_name.data
        queried_task.text = form.text.data
        db.session.commit()
        flash('Task has been updated.', 'success')
        return redirect(url_for('tasks.task', task_id=queried_task.id))

    elif request.method == 'GET':
        form.task_name.data = queried_task.task_name
        form.text.data = queried_task.text

    return render_template('create_task.jinja2',
                           title='Update Task',
                           legend='Update Task',
                           form=form, )


@tasks.route("/task/<int:task_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)

    # verify that the user requesting to update is the original author
    if task.author != current_user:
        abort(403)

    db.session.delete(task)
    db.session.commit()
    flash('Task has been deleted!', 'success')
    return redirect(url_for('main.index'))


@tasks.route("/task/new", methods=['GET', 'POST'])
@login_required
def new_task():
    form = TaskForm()
    if form.validate_on_submit():
        task = Task(task_name=form.task_name.data,
                    text=form.text.data,
                    author=current_user, )
        db.session.add(task)
        db.session.commit()
        flash(f'Task has been added.', 'success')
        return redirect(url_for('main.index'))

    return render_template('create_task.jinja2',
                           title='New Task',
                           legend='New Task',
                           form=form, )

tracktask/users/routes.py
"""
Title:      routes.py
Desc:       contains route functions that pertain to the users model
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from tracktask import db, bcrypt
from tracktask.models import User, Task
from tracktask.users.forms import (RegistrationForm, LoginForm,
                                   UpdateAccountForm, )
from tracktask.users.utils import save_picture

users = Blueprint('users', __name__)


# - - - - - - - - - - - - - - Account Methods - - - - - - - - - - - - - - #


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')

        user = User(user_name=form.user_name.data,
                    user_email=form.user_email.data,
                    password=hashed_password, )

        db.session.add(user)
        db.session.commit()

        flash(f'Your account has been created!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.jinja2', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(user_email=form.user_email.data).first()

        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(
                url_for('main.index'))
        else:
            flash(f'Login failed. Please check email and password', 'danger')
    return render_template('login.jinja2', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required  # needs to be after @app.route deco
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():

        if form.user_image.data:
            picture_file = save_picture(form.user_image.data)
            current_user.user_image = picture_file

        current_user.user_name = form.user_name.data
        current_user.user_email = form.user_email.data
        db.session.commit()
        flash('Account info updated.', 'success')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.user_name.data = current_user.user_name
        form.user_email.data = current_user.user_email

    image_file = url_for('static',
                         filename=f'profile_pics/{current_user.user_image}', )
    return render_template('account.jinja2',
                           title='Account',
                           image_file=image_file,
                           form=form, )


@users.route("/user/<string:user_name>")
def user_tasks(user_name):
    page = request.args.get('page', 1, type=int, )
    user = User.query.filter_by(user_name=user_name).first_or_404()
    tasks = Task.query.filter_by(author=user) \
        .order_by(Task.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('user_tasks.jinja2',
                           tasks=tasks,
                           user=user, )

tracktask/templates/about.jinja2
{% extends 'layout.jinja2' %}

{% block content %}
    <h1>About Page</h1>
{% endblock content %}

tracktask/templates/account.jinja2
{% extends 'layout.jinja2' %}

{% block content %}
    <div class = "content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
                <div class="media-body">
                  <h2 class="account-heading">{{ current_user.user_name }}</h2>
                  <p class="text-secondary">{{ current_user.user_email }}</p>
            </div>
        </div>
        <!-- FORM HERE -->
         <div class="content-section">
            <form method="POST" action="" enctype="multipart/form-data">
                {{  form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Info</legend>
                    <div class="form-group">
                        {{  form.user_name.label(class="form-control-label") }}

                        {% if form.user_name.errors %}
                            {{ form.user_name(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.user_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{  form.user_name(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{  form.user_email.label(class="form-control-label") }}
                        {% if form.user_email.errors %}
                            {{ form.user_email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.user_email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{  form.user_email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.user_image.label() }}
                        {{ form.user_image(class="form-control-file") }}
                        {%  if form.user_image.errors %}
                            {% for error in form.user_image.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        {%  endif %}
                    </div>

                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

tracktask/templates/create_task.jinja2
{% extends 'layout.jinja2' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{  form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>

                <div class="form-group">
                    {{  form.task_name.label(class="form-control-label") }}
                    {% if form.task_name.errors %}
                        {{ form.task_name(class="form-control form-control-lg is-invalid") }}

                        <div class="invalid-feedback">
                            {% for error in form.task_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>

                    {% else %}
                        {{  form.task_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{  form.text.label(class="form-control-label") }}
                    {% if form.text.errors %}
                        {{ form.text(class="form-control form-control-lg is-invalid") }}

                        <div class="invalid-feedback">
                            {% for error in form.text.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>

                    {% else %}
                        {{  form.text(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

        </form>
    </div>
{% endblock content %}

tracktask/templates/index.jinja2
{% extends 'layout.jinja2' %}

{% block content %}
    {% for task in tasks.items %}
        <article class="media content-section">

            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_tasks', user_name=task.author.user_name) }}">{{ task.author.user_name }}</a>
                <small class="text-muted">{{ task.date_posted.strftime('%b-%d-%Y') }}</small>
            </div>

            <div>
                <img class="rounded-circle article-image" src="{{ url_for('static', filename='profile_pics/' + task.author.user_image) }}">

                <div class="media-body">
                    <p class="article-content">Description: {{task.text}}</p>
                    <p class="article-content">Date Posted: {{task.date_posted.strftime('%b-%d-%Y') }}</p>
                    {% if task.status == True %}
                        <p class="article-content">Completed on {{task.date_complete}}</p>
                    {% else %}
                        <p class="article-content">Incomplete</p>
                    {% endif %}
                </div>
            </div>

        </article>
    {% endfor %}

    {% for page_num in tasks.iter_pages() %}
        {% if page_num %}
            {% if tasks.page == page_num %}
                <a class="btn btn-dark mb-4" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-dark mb-4" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

{% endblock content %}

tracktask/templates/layout.jinja2
<!DOCTYPE html>
<html lang="en">
    <head>
         <!-- Bootstrap CSS -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
         <!-- Style CSS -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">

        {% if title %}
            <title>TrackTask - {{ task_name }}</title>
        {% else %}
            <title>TrackTask</title>
        {% endif %}
    </head>

    <body>
        <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
              <a class="navbar-brand mr-4" href="/">TrackTask</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Home</a>
                  <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>

                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('tasks.new_task') }}">New Task</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    {% endif %}
                </div>
              </div>
            </div>
          </nav>
        </header>

        <main role="main" class="container">
          <div class="row">
            <div class="col-md-8">
                {%  with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
              <div class="content-section">
                <h3>Tasks Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Tasks</li>
                    <li class="list-group-item list-group-item-light">All Completed Tasks</li>
                    <li class="list-group-item list-group-item-light">All Incomplete Tasks</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                  </ul>
                </p>
              </div>
            </div>
          </div>
        </main>

         <!-- Bootstrap CSS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </body>
</html>

tracktask/templates/login.jinja2
{% extends 'layout.jinja2' %}

{% block content %}
    <h1>Login</h1>
    <div class="content-section">
        <form method="POST" action="">
            {{  form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign in to your account</legend>

                <div class="form-group">
                    {{  form.user_email.label(class="form-control-label") }}
                    {% if form.user_email.errors %}
                        {{ form.user_email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.user_email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{  form.user_email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{  form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{  form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up now</a>
        </small>
    </div>
{% endblock content %}

tracktask/templates/register.jinja2
{% extends 'layout.jinja2' %}

{% block content %}
    <h1>Register</h1>
    <div class="content-section">
        <form method="POST" action="">
            {{  form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create a new account</legend>
                <div class="form-group">
                    {{  form.user_name.label(class="form-control-label") }}

                    {% if form.user_name.errors %}
                        {{ form.user_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.user_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{  form.user_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{  form.user_email.label(class="form-control-label") }}
                    {% if form.user_email.errors %}
                        {{ form.user_email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.user_email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{  form.user_email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{  form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{  form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{  form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{  form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account?<a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

tracktask/templates/task.jinja2
{% extends 'layout.jinja2' %}

{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-image" src="{{ url_for('static', filename='profile_pics/' + task.author.user_image) }}">
        <div class="media-body">
            <div class="article-metadata">
                <h2>{{ task.task_name }}</h2>
                <p class="article-title">Description: {{task.text}}</p>
                <p class="article-content">Date Posted: {{task.date_posted.strftime('%b-%d-%Y') }}</p>

                {% if task.status == True %}
                    <p class="article-content">Completed on {{task.date_complete}}</p>
                {% else %}
                    <p class="article-content">Incomplete</p>
                {% endif %}

                {% if task.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('tasks.update_task', task_id=task.id) }}">Update</a>
{#                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('tasks.delete_task', task_id=task.id) }}">Delete</a>#}
                        <! -- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal">Delete</button>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}

            </div>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Task?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('tasks.delete_task', task_id=task.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
            <!-- End Modal content-->
        </div>
    </div>
    <!-- End Modal -->
{% endblock content %}

tracktask/templates/user_tasks.jinja2
{% extends 'layout.jinja2' %}

{% block content %}
    <h1 class="mb-3">Tasks by {{ user.user_name }} ({{ tasks.total }})</h1>

    {% for task in tasks.items %}
        <article class="media content-section">
            <img class="rounded-circle article-image" src="{{ url_for('static', filename='profile_pics/' + task.author.user_image) }}">

            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_tasks', user_name=task.author.user_name) }}">{{ task.author.user_name }}</a>
                    <small class="text-muted">{{ task.date_posted.strftime('%b-%d-%Y') }}</small>
                </div>

                <h2><a class="article-title" href="{{ url_for('tasks.task', task_id=task.id) }}">{{ task.task_name }}</a></h2>
                <p class="article-content">Description: {{task.text}}</p>
                <p class="article-content">Date Posted: {{task.date_posted.strftime('%b-%d-%Y') }}</p>
                {% if task.status == True %}
                    <p class="article-content">Completed on {{task.date_complete}}</p>
                {% else %}
                    <p class="article-content">Incomplete</p>
                {% endif %}
            </div>

        </article>
    {% endfor %}

    {% for page_num in tasks.iter_pages() %}
        {% if page_num %}
            {% if tasks.page == page_num %}
                <a class="btn btn-dark mb-4" href="{{ url_for('users.user_tasks', user_name=user.user_name, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-dark mb-4" href="{{ url_for('users.user_tasks', user_name=user.user_name, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

{% endblock content %}